openapi: 3.0.3
components:
  schemas:
    Cliente:
      type: object
      properties:
        age:
          type: number
        balance:
          type: number
        campaign:
          type: number
    Respuesta:
      type: object
      properties:
        probabilidad_si:
          type: number
